apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: mlflow-runs
  namespace: mlflow-system
spec:
  chart:
    repo: mlflow-test
    url: https://github.com/dusty-82/
    version: 0.0.3
